### PR TITLE
Set keepalive to 10s

### PR DESCRIPTION
**Pull request by jctooley**
Fixes issue #84

### CODE REVIEW

**Comment by jctooley** [comment]
Reference to  same error on the [umqtt library](https://github.com/micropython/micropython-lib/issues/466)

**Comment by Maffsie** [comment]
Confirmed, this fixes my Enviro Weather as well.

**Comment by nopuk** [comment]
> Confirmed, this fixes my Enviro Weather as well. Upgraded from the firmware it shipped with to 0.0.8, MQTT uploads broke. After an hour's digging I stumbled across this PR and, indeed, adding a keepalive parameter to connect() fixed it and all pending uploads completed.

@Maffsie I have an Eviro weather too, and experienced a similar issue, however my weather is unable to get past about 7-8hrs of uploads to mqtt - it just hangs with the log giving no new info, tap the poke button all back to normal for another 7 or 8 hours. Its maddening. Does yours works for days on end given battery? I am doing uplaods each 15min while testing it.

**Comment by Maffsie** [comment]
> > Confirmed, this fixes my Enviro Weather as well. Upgraded from the firmware it shipped with to 0.0.8, MQTT uploads broke. After an hour's digging I stumbled across this PR and, indeed, adding a keepalive parameter to connect() fixed it and all pending uploads completed.
> 
> 
> 
> @Maffsie I have an Eviro weather too, and experienced a similar issue, however my weather is unable to get past about 7-8hrs of uploads to mqtt - it just hangs with the log giving no new info, tap the poke button all back to normal for another 7 or 8 hours. Its maddening. Does yours works for days on end given battery? I am doing uplaods each 15min while testing it.

@nopuk Mine has been doing exactly the same, though it goes silent after about 6 hours. I'm doing uploads every 15m with data collection every 5m. I just assumed it's related to the RTC bug (I forget the bug number and I'm on my phone so can't look it up) and have been waiting for a fix on that.

Curiously, the 0.0.2 firmware worked fine, and I would just go back to that, but I switched the battery out for a LiIon battery and a LiPo Amigo, so I need the voltage reporting from 0.0.8 to know when to recharge it!

@helgibbons is this an example of the RTC wake-up issue, or should a new issue be opened for this?

**Comment by helgibbons** [comment]
@Maffsie - adding the `keepalive` parameter did seem to improve uptime for me, but my Weather is still crashing every day or so with mqtt. Feel free to open another issue or contribute to an existing one as appropriate - @lowfatcode is back next week so we should hopefully see some fixes soon :)

**Comment by jctooley** [comment]
Mine runs longer than 6 hours although I have to admit, the connection to WiFi is flaky as it doesn't get a connection every time. I currently log every 5 mins and upload every reading. I know this is power hungry but it is currently sat in my office where I can easily charge the battery.

**Comment by nopuk** [comment]
Perhaps a silly question to ask,  but does anyone run their enviro weather
in such a way that they don't have to worry about it giving up a few hours
later.  I kinda feel I purchased a product that doesn't do its one basic
function.  The pimoroni product page sells this.

**Comment by MrDrem** [comment]
Switching to 10 resolved the uploads failing issue, 60 may make it more stable. It was certainly better under 0.0.2, but I don't know  if that was the difference.

Its certainly worth testing (maybe with a pair of devices, once set to 10 and one to 60). Easier for you than us :)

**Comment by ZodiusInfuser** [comment]
As of v0.0.9 the keepalive value is 60 seconds, so I will close this PR. If you feel it should be 10 seconds, please re-open it.

**Pull request closed without merging**
