### PR TITLE
Add support for MQTT pver SSL and update to attemp disconnects and extra loggin on mqtt failures

### PR DESCRIPTION
**Pull request by dave-ct**
Add support for a local mqtt broke that uses ssl.  Allow user to add in their ca,crt file and if exists use SSL for mqtt uploads.

Relates to issue #122

### CODE REVIEW

**Comment by ZodiusInfuser** [comment]
Thanks for this. A few additions:

- Could you add this new mqtt parameter to the config_template, such that it will get picked up when someone newly provisions a board.
- For the check of the parameter's value, there should first be a check (or a try except) to handle if/when that parameter is not present within a user's config.

**Comment by dave-ct** [comment]
Added a couple more updates here, still testing to see if they work.

**Comment by ZodiusInfuser** [comment]
Thank you for the additions. Any chance you can raise the logging change as a separate PR to this please? Makes it easier on my end to evaluate and approve the changes.

**Comment by dave-ct** [comment]
@ZodiusInfuser  have reverted from here and created new pull request https://github.com/pimoroni/enviro/pull/128

Will also clean this pull request so it just relates to mqtt

**Comment by ZodiusInfuser** [comment]
Thanks for tidying this up. There's a few things from a code standpoint that I'd like to do, but they can be done after this is merged in 🙂

**Comment by ZodiusInfuser** [comment]
Specifically, turn that exception logging line into a neater function call, and correct a few typos in the comments

**Pull request merged**
