### PR TITLE
Store multiple readings in each log file

### PR DESCRIPTION
**Pull request by guruthree**
If no upload destination/frequency is specified, logged readings are instead stored locally.
Currently the Enviro firmware will create one file for each logged reading. This is unwieldy both for downloading and then later processing the data.

The existing `save_reading` function will currently append to an existing log file, but on each call used a different `readings_filename`, resulting in one file per reading. I propose the introduction of a `readings_per_file` configuration item that is used in creating a multi-use filename so that multiple readings can be properly appended into files, keeping both file sizes and file numbers manageable.

The new filename retains the same format, but rather than using the current time, a filename time is calculated using `floor()` on the Unix timestamp divided by (reading frequency × readings per file × 60), and then multiplied back up by the latter, similar to how the numbers of minutes into the day is calculated. For example, if the reading interval is 15 minutes and the number of readings per file is 96, then the filename for today would be `readings/2022-12-30T00_00_04Z.txt`.

The new configuration item is exposed during provisioning when the 'Never' upload option is selected.

### CODE REVIEW

**Comment by ZodiusInfuser** [comment]
Thanks for raising this pull request! We haven't had that many users make use of the local logging feature, so the issue of file count wasn't really considered by us. I appreciate you including the provisioning options for it too!

I will test this code out and let you know if there's any tweaks that need to be made. At first glance some of the numbers in the comments seem to have the wrong units. `15 per minute` for instance.

**Comment by nils-s** [comment]
Ran into the same problem and found this issue, which seems to have gone stale.

Judging by the verbiage of the comments around the `save_reading` function in *enviro/\_\_init\_\_.py* (specifically the comment on line 368), I'd say a fix could actually be a lot simpler than what is provided by this PR:
instead of using `helpers.datetime_file_string()` to generate the filename, simply use `helpers.date_string()` (line 370), which would create one file per day, with all the logs for that day (consistent with the comment on line 368).

@ZodiusInfuser: this would fix (or at least alleviate) the issue of one file per reading, albeit without the configurable number of readings per file (as suggested and provided by @guruthree). Should I create a PR for that, or is this PR still on track?

**Comment by guruthree** [comment]
Yes your approach is a lot simpler. I designed this PR specifically to be similar to the way uploads work, sort of treating the stored file as if it were upload target, dumping all the stored readings into that file the same way they're uploaded in a group. Possibly not the most straightforward of approach, but it hopefully provides a consistent experience between choosing upload and store to file for users.

**Comment by guruthree** [comment]
Closed per #194

Edit: the code for this now lives in https://github.com/guruthree/enviro/tree/multiple_readings

**Pull request closed without merging**
